Feature/manage location
2110336-2565-2/sec33_Group4_BookBix_Backend pull request #35
Opened 2023-03-30 06:12 UTC by NatananPh

## As a Provider I want to manage the detail of organized location So that location detail is up-to-date as soon as possible and the customer can see the detail correctly

### Main tasks
- [x] (Create POST API for creating a location)
- [x] (Create PUT API for updating a location by id)
- [x] (Create DELETE API for removing a location by id)
--------------------------------------------------------------
### Miscellaneous tasks
- [x] (Create GET API for get all locations and get a location by id)
- [x] (Create GET API for get a customer's infrmation by id)
## Testing
### PUT/DELETE API for updating/removing a location
Detail: https://sw2project2022-2.atlassian.net/jira/software/projects/SPBX/boards/1?assignee=635cdf65d66d8108a1246184&selectedIssue=SPBX-136

### POST API for creating a location
Detail: https://sw2project2022-2.atlassian.net/jira/software/projects/SPBX/boards/1?assignee=635cdf65d66d8108a1246184&selectedIssue=SPBX-135

### GET API for get all locations
Endpoint: 
```
{{URL}}/locations
```

### GET API for get a location by id
Endpoint
```
{{URL}}/locations:locationId
```
Example
```
{{URL}}/locations/000000000004000000000001
```

### GET API for get a customer's infrmation by id (Get customer profile)
Endpoint
```
{{URL}}/customers/:customerId
```
Example
```
{{URL}}/customers/000000000001000000000001
```

2023-03-31 01:28 UTC, chanakorn-github requested changes

2023-03-31 01:28 UTC, chanakorn-github commented on src/customers/customers.service.ts
> +  async getProfile(customerId: string) {
ชื่อ function ปกติถ้า return object customer เราจะใช้ชื่อว่า getCustomer()แต่ไม่มีปัญหาเรื่องการทำงานคิดว่าแค่แก้ชื่อก็พอ

2023-04-01 08:31 UTC, NatananPh commented
แก้ไขเรียบร้อยคับ🍻

2023-04-01 08:41 UTC, chanakorn-github approved these changes

2023-04-01 09:46 UTC, merged